<a href="https://colab.research.google.com/github/Azamat2023/BlogProject/blob/master/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22mohirdev_NumPy_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [ ]:
import numpy as np
np.show_config

<function numpy.__config__.show(mode='stdout')>

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [ ]:
# prompt: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9

import numpy as np

# versiya va konfiguratsiyani tekshiring.
np.show_config

# Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!
my_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
my_array = np.array(my_list)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



`💡Ishora` np.zeros

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [ ]:
arr = np.zeros(10)
arr.size
arr.itemsize

8

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [ ]:
arr1 = np.zeros(12)
arr1[5] = 1
arr1

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [ ]:
arr2 = np.arange(20, 59)
arr2

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [ ]:
arr2[::-1]

array([58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42,
       41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25,
       24, 23, 22, 21, 20])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
arr3 = np.arange(12, 21).reshape(3, 3)
arr3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [ ]:
my_list1 = [3, 7, 0, 0, 9, 0]
arr4 = np.array(my_list1)
np.nonzero(arr4)

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [ ]:
random_numbers = np.random.random(size=(2,2,2))
random_numbers

array([[[0.09126259, 0.39938628],
        [0.49874581, 0.26042572]],

       [[0.99716266, 0.42997318],
        [0.81159816, 0.40525608]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [ ]:
random_numbers2 = np.random.random(size=(9,9))
max_number = random_numbers2.max()
min_number = random_numbers2.min()
max_number, min_number

(0.99932410662833, 0.002519669272412872)

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [ ]:
False

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
arr5 = np.random.random(18).reshape(6, 3)
arr6 = np.random.random(12).reshape(3, 4)
res = np.dot(arr5, arr6)
res

array([[1.43875064, 1.70755627, 1.22852599, 1.33024237],
       [1.19576456, 1.30714322, 0.97151506, 1.16440209],
       [0.43592159, 0.72673145, 0.45975118, 0.29341285],
       [0.78577154, 0.81411912, 0.67195539, 0.7855954 ],
       [1.20938886, 1.49207293, 1.08938021, 1.08654923],
       [0.86987693, 1.12581666, 0.65854088, 0.76254163]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

10

#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [ ]:
arr7 = np.random.random(2)
arr8 = np.random.random(2)
arr7 > arr8, arr7 >= arr8, arr7 < arr8, arr7 <= arr8

(array([ True, False]),
 array([ True, False]),
 array([False,  True]),
 array([False,  True]))

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
"invalid value"
"divide by zero"
"array([-9.22337204e+18])"

'array([-9.22337204e+18])'

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [ ]:
arr9 = np.array([5, 8, 12, 16, 17])
arr10 = np.array([12, 17])
res = np.intersect1d(arr9, arr10)
res

array([12, 17])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [ ]:
arr11 = np.random.random(10)
arr11 // 1, np.floor(arr11), arr11.astype(np.int64), np.trunc(arr11)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [ ]:
arr12 = np.arange(0, 2, 0.24).reshape(3, 3)
arr12

array([[0.  , 0.24, 0.48],
       [0.72, 0.96, 1.2 ],
       [1.44, 1.68, 1.92]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [ ]:
arr13 = np.random.random(10)
np.sort(arr13)

array([0.11528936, 0.14601276, 0.26409247, 0.49121794, 0.67028169,
       0.70588419, 0.74452868, 0.89124538, 0.9097068 , 0.9423678 ])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [ ]:
a = np.arange(12)
b = np.arange(15)
np.array_equal(a, b)

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [ ]:
arr14 = np.random.random(18).reshape(6, 3)
arr15 = np.random.random(12).reshape(3, 4)
res = np.dot(arr14, arr15)
res

array([[1.07342026, 0.65374997, 0.77400211, 0.90225326],
       [1.33054633, 0.89904301, 1.03313278, 1.05349677],
       [0.69036425, 1.01408765, 0.99892401, 0.79441058],
       [1.3509948 , 1.20224734, 1.29246115, 1.10287287],
       [1.38571611, 1.09817708, 1.21072622, 0.99679222],
       [0.7969403 , 1.11946229, 1.10987175, 0.89346577]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [ ]:
a = np.random.random(5)
mask = np.max(a) == a
a[mask] = 0
a

array([0.47390707, 0.        , 0.6180286 , 0.38207461, 0.52019902])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [ ]:
date_today = np.datetime64('today', 'D')
print('Bugun', date_today)
print('Kecha', date_today - 1)
print('ERtaga', date_today + 1)

Bugun 2025-01-15
Kecha 2025-01-14
ERtaga 2025-01-16


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [ ]:
dates = np.arange('2016-01', '2016-02', dtype='datetime64[D]')
dates

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [ ]:
arr16 = np.random.random(10)
arr16 // 1, np.floor(arr16), arr16.astype(np.int64), np.trunc(arr16)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]))

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [ ]:
a = np.arange(10)
b = np.add.reduce(a)
b

45

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [ ]:
vektor = np.array([1, 2, 3, 4, 5])
# Sintaksisi: np.insert(arr, index, values)
result = np.insert(vektor, range(1, len(vektor) * 2, 2), 0)
print(result)

1
2
3
4
5


#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [ ]:
from numpy.lib import stride_tricks
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
b = stride_tricks.as_strided(a, shape=(len(a)-3, 4), strides=(a.itemsize, a.itemsize))
b

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [ ]:
# prompt: a = np.array([3, 5, 7, 8, 5, 3, 9, 5, 3, 8, 10, 7, 3])

import numpy as np
a = np.array([3, 5, 7, 8, 5, 3, 9, 5, 3, 8, 10, 7, 3])
# Har bir sonning takrorlanishini hisoblash
count = np.bincount(a)

# Eng ko'p takrorlangan sonni aniqlash
most_frequent_value = np.argmax(count)

# Takrorlanish soni
frequency = count[most_frequent_value]

print(f"Eng ko'p takrorlangan son: {most_frequent_value}")
print(f"Uning takrorlanish soni: {frequency}")

Eng ko'p takrorlangan son: 3
Uning takrorlanish soni: 4


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`